version: '3.9'
networks:
  default:
    name: 'mingo-databases'
services:
  redis:
    image: redis:6.2.4
    container_name: 'redis'
    volumes:
      - redis_data:/redis/data/db
      - ./redis.conf:/redis.conf
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: ['redis-server', '/redis.conf']
  mongo:
    image: mongo:4.4
    container_name: 'mongo'
    volumes:
      - mongo_data:/mongodb/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    env_file:
      - './mongo.env'
    restart: unless-stopped
volumes:
  redis_data:
  mongo_data:
